name: vulkan-cts
base: core24
confinement: classic
lint:
  ignore:
    - metadata
platforms:
  amd64:
    build-on: [amd64]
  arm64:
    build-on: [amd64, arm64]
version: '1.4.5'
summary: Khronos Vulkan Conformance Test Suite
description: |
  Baseline snap for the Khronos Vulkan CTS. Builds the deqp-vk
  test binary from source via CMake and ships an executable for running tests.

apps:
  test:
    command: test
  list-tests:
    command: list_tests

parts:
  test-conformance:
    source: bin/
    plugin: dump
    stage:
      - test

  list-tests:
    source: bin/
    plugin: dump
    stage:
      - list_tests

  vulkan-cts:
    plugin: nil
    source: https://github.com/KhronosGroup/VK-GL-CTS.git
    source-branch: vulkan-cts-$SNAPCRAFT_PROJECT_VERSION
    source-type: git
    build-attributes:
      - enable-patchelf
    build-packages:
      - build-essential
      - cmake
      - python3-pip
      - meson
      - pkg-config
      - libpng-dev
      - libvulkan-dev
      - mesa-common-dev
      - python3-lxml
    stage-packages:
      - libgl1
      - libvulkan1
      - libpng16-16t64
      - libx11-6
      - libxcb1
      - libxext6
      - libwayland-client0
    override-build: |
      set -eux

      python3 external/fetch_sources.py
      mkdir build && cd build

      # Different archs need different buildflags; only set arch flags
      # when building natively to avoid passing host-incompatible -march.
      CMAKE_CLANG_FLAGS=""
      if [ "$CRAFT_ARCH_BUILD_FOR" == "amd64" ] && [ "$CRAFT_ARCH_BUILD_ON" == "amd64" ]; then
          CMAKE_CLANG_FLAGS=-m64
      elif [ "$CRAFT_ARCH_BUILD_FOR" == "arm64" ] && [ "$CRAFT_ARCH_BUILD_ON" == "arm64" ]; then
          CMAKE_CLANG_FLAGS=-march=armv8-a
      fi

      cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS=$CMAKE_CLANG_FLAGS -DCMAKE_CXX_FLAGS=$CMAKE_CLANG_FLAGS
      # 64GB RAM wasn't enough for -j. Add nproc
      make -j`nproc`

      mkdir -p "${CRAFT_PART_INSTALL}/usr/bin/"
      cp "${SNAPCRAFT_PART_BUILD}/build/external/vulkancts/modules/vulkan/deqp-vk" "${CRAFT_PART_INSTALL}/usr/bin/"

      # Copy required data files and mustpass lists
      mkdir -p "${CRAFT_PART_INSTALL}/usr/share/vulkan-cts/"
      cp -r "${SNAPCRAFT_PART_BUILD}/external/vulkancts/data" "${CRAFT_PART_INSTALL}/usr/share/vulkan-cts/" || true
      cp -r "${SNAPCRAFT_PART_BUILD}/build/external/vulkancts/modules/vulkan/vulkan" "${CRAFT_PART_INSTALL}/usr/share/vulkan-cts/" || true
      cp -r "${SNAPCRAFT_PART_BUILD}/external/vulkancts/mustpass" "${CRAFT_PART_INSTALL}/usr/share/vulkan-cts/" || true
